spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "1.0"


accounts:
  message: "PROD"
  contactDetails:
    name: "testname - prod"
    email: "testemail - prod"
  onCallSupport:
    - 789
    - 111